### ISSUE TITLE
Aggregate Culture Mauricie events (Shawinigan, Cogecoa and Tourisme Mauricie) and Caligram events using APIs

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#72]
Our next CMS client is Culture Mauricie.

They were using Caligram CMS, and are now switching to Footlight CMS because Caligram is closing.

In the past, they were loading events from these 3 APIs.  Our challenge is to design and build a tool to load events from APIs in a generic way so that we can repeat with other customers without releasing new code.

This can be split into separate issues to track work, but this issue should be kept as the high-level issue for the design of the generic solution.

# Shawinigan

Culture Shawinigan is a city arts council for the town of Shawinigan

**API** to a local ticketing platform
https://api.ticketacces.net/v1/showtimes?KeyID=CULTURESHAWI&KeySecret=wMalrXUtnFEMIK7PDENGbPxRfiGY&Domains=shawinigan.ticketacces.net&Language=fr

**Important**: **this API must not be called more than 2 or 3 times a day.**

# Cogeco
https://www.amphitheatrecogeco.com/
l’Amphithéâtre Cogeco is a theatre in a city called Trois-Rivieres, one of the oldest cities in Quebec.

**API** http://amphitheatrecogeco.com/json?module=spectacle&method=getspectacles

FYI: This site is already being crawled by Footlight Console as an experiment. https://console.footlight.io/events?seedurl=amphitheatrecogeco-com&view=list

 
# Tourisme
https://www.tourismemauricie.com/
For a short while we will load event from this site, but a few months later they will also switch to Footlight CMS as a fourth client (we will then have to figure out how to share events between calendars in the CMS.)

**API** https://www.tourismemauricie.com/wp-admin/admin-ajax.php?action=caligram

**Comment by sahalali** [comment]
@saumier Can we discuss this in detail after the standup?

**Comment by sahalali** [comment]
@tammy-culture Firewall is blocking to access the URL for Tourisme Mauricie  https://www.tourismemauricie.com/wp-admin/admin-ajax.php?action=caligram.

Can you please see if someone can help us to get access to the URL?

**Comment by tammy-culture** [comment]
Hi Suhail,  I will look into this and get back to you.  Thanks.

**Comment by saumier** [comment]
@sahalali @dev-aravind I suggested in the standup this morning that you work together on this one.  Something that could be done in the analysis is to document the mapping between each external API source and the CMS.  

A question that we should ask ourselves in the analysis is whether we should use the 3 APIs or instead crawl the website with Console.  

FYI @tammy-culture has already asked Kim to crawl Cogeco has an experiment https://console.footlight.io/events?seedurl=amphitheatrecogeco-com&view=list so we can compare the Cogeco API versus crawling Cogeco website using Console to decide which is better. If the data in the Cogeco API is very similar to that obtained by the Console, then we should choose the API for reliability and maintainability. But if the API has many fewer fields then we should consider the Console approach. So to answer this question we will need to know the differences as part of the analysis.

**Comment by tammy-culture** [comment]
@sahalali @saumier I spoke with with Tourism Mauricie this morning and they will ask their tech team to provide access to theire API.  I will keep you all posted.

**Comment by dev-aravind** [comment]
@saumier First draft of the mapping between fields:

https://docs.google.com/spreadsheets/d/1gORhHpQrpKw4D9bJquil6GbNfpRM-F2R-3rSH1LCKb8/edit#gid=0

**Comment by saumier** [comment]
@dev-aravind Here are the links to the websites.

https://www.amphitheatrecogeco.com

**Comment by dev-aravind** [comment]
@saumier [second draft](https://docs.google.com/spreadsheets/d/1gORhHpQrpKw4D9bJquil6GbNfpRM-F2R-3rSH1LCKb8/edit#gid=0) of the mapping between fields.

**Comment by tammy-culture** [comment]
@sahalali, @dev-aravind 

Hello, I just heard back from Tourism Mauricie and they said to try the the api again.  Let me know how it goes.

Thanks,
Tammy

**Comment by sahalali** [comment]
@tammy-culture Thanks for the update. It works now.

**Comment by dev-aravind** [comment]
@sahalali I've added Tourism Mouricie data too to our mapping.

**Comment by tammy-culture** [comment]
@sahalali 

Hello everyone, I received an important note in regards to the Culture Shawinigan API.
The API should **not be called more than 2 or 3 times a day. (Very important).**

Thanks.

**Comment by saumier** [comment]
@dev-aravind @sahalali To start the project with Culture Mauricie @tammy-culture would like us to start with the Amphithéâtre Cogeco API and load it into the CMS as soon as possible so she can work with them to setup their calendar.  I propose we use this API to continue learning how best to do this, and create a separate issue to track.

**Comment by tammy-culture** [comment]
@sahalali @saumier Please let me know if this is the right place to bring this issue up. It was brought to my attention by our new client, that the API used to load events for Culture Shawinigan does not include all the events listed on their site: https://cultureshawinigan.ca. 

That is because the API used is from a local ticketing platform, so only ticketed paid events are covered.  It does not include any of the free events that are listed on the Culture Shawinigan site.  The client would like to know what potential solutions and options could be available.

**Comment by sahalali** [comment]
@saumier We have the option to import events and related entities using an Excel sheet in a specific format.
We can share the footlight-cms supported format. I would suggest the development team do the import to CMS because lets validate the data before importing.

**Comment by sahalali** [comment]
@tammy-culture I've encountered the same issue with accessing the API https://www.tourismemauricie.com/wp-admin/admin-ajax.php?action=caligram. 

The error message is "Access denied".
I noticed this issue today, not sure if it is happening due to the change in IP and location.

**Comment by tammy-culture** [comment]
@sahalali Can you provide a screen shot of the error message and I will send it along.  Thanks.

**Comment by sahalali** [comment]
@tammy-culture Please find the screenshot of the error page.
<img width="960" alt="Screenshot 2023-12-13 at 10 54 17 AM" src="https://github.com/culturecreates/footlight-aggregator/assets/139197166/ed861695-8be2-4248-bcc5-d03a6107bcdd">

**Comment by tammy-culture** [comment]
@sahalali Thank you.

**Comment by tammy-culture** [comment]
@sahalali I have another api to analyze and integrate to the Culture Mauricie calendar.  It is an API from Culture Trois Rivières. Please let me know if it is usable. Thanks.

https://api.tuxedoticket.ca/documentation

**Comment by sahalali** [comment]
This is the API documentation we prepared for cms-api and admin-api. To get data using this URL, we will need to authenticate. So if the client could provide us a login credential, then we could start analyzing the data.

**Comment by tammy-culture** [comment]
@sahalali The Tourism Mauricie api should work now.

**Comment by sahalali** [comment]
@tammy-culture 
The issue still exists at my end. 
<img width="945" alt="Screenshot 2023-12-14 at 10 01 58 AM" src="https://github.com/culturecreates/footlight-aggregator/assets/139197166/0dcd6f44-ff2d-48b2-8ec3-9f00405830be">

**Comment by tammy-culture** [comment]
Thanks @sahalali I will look into it.

**Comment by tammy-culture** [comment]
@sahalali Hi, the Tourism Mauricie should be working.  Thanks.

**Comment by sahalali** [comment]
Estimation: 7 days
1. Add support to upload RDF using footlight-aggregator (RDF data following Schema.org).
2. Prepare GitAction:
    a. Run Ontotext/refine
    b. Prepare and verify mapping files
    c. Convert data to RDF using REFINE.
    d. Call Footlight-aggregator API to update events.

The confidence of estimation is Medium, the estimation may vary a little durign development.

**Comment by sahalali** [comment]
This is ready to schedule.

**Comment by saumier** [comment]
@sahalali Let me know as soon as you have the github workflow that runs ontotext/refine with the command **transform** passing in the csv filename and mapping filename.  I will use the same workflow for importing Ville de Laval.

**Comment by tammy-culture** [comment]
@sahalali @troughc Is there a way for me to get a google sheet copy of the data available in each of the 2 APIs? (Shawinigan and Cogeco). Many thanks.

**Comment by sahalali** [comment]
@tammy-culture The Shawningan response in XML format and Cogeco in JSON. As we have not imported both sources into CMS, we will need to convert the data to CSV.

**Comment by tammy-culture** [comment]
@sahalali Is this another way that I can view the data that is easier for you before we load it into the CMS?

**Comment by saumier** [comment]
@tammy-culture Have you seen this mapping done by Dev? It has a single event as example. https://docs.google.com/spreadsheets/d/1gORhHpQrpKw4D9bJquil6GbNfpRM-F2R-3rSH1LCKb8/edit#gid=0

**Comment by tammy-culture** [comment]
> @tammy-culture Have you seen this mapping done by Dev? It has a single event as example. https://docs.google.com/spreadsheets/d/1gORhHpQrpKw4D9bJquil6GbNfpRM-F2R-3rSH1LCKb8/edit#gid=0

Yes I have thank you. @sahalali What I actually need rather than all the data are just the concepts from each API mapping to event types (additionalType in Footlight CMS):
 
- Tourisme Mauricie (categorie)
- Cogeco (category.name)
- Shawinigan (eventgenrename, eventratingname, eventsubgenrename, showtimemaincategoryname)

Can you provide this in a spreadsheet. please.

Many thanks,
Tammy

**Comment by sahalali** [comment]
@troughc Please find the list of event types under each API in [this Google sheet](https://docs.google.com/spreadsheets/d/1RY8lxcxzajwRF8JC3aBUg0IcV9k8WOEBUD3pVHUAj9M/edit#gid=1470320955).

The Tourisme Mauricie is accessible to me today, So I've added event types from a saved old response.

**Comment by sahalali** [comment]
@tammy-culture The Tourisme API is not accessible to me. Can you please help me out to get it accessible?
Attached is the screenshot of the error message. 


![Image](https://github.com/culturecreates/footlight-aggregator/assets/139197166/698b6157-34da-472c-8b0e-d6ee96cc8964)

**Comment by sahalali** [comment]
@tammy-culture To bypass the issue with repeated IP address changes. We can use our staging-server-3 to call the Tourisme Mauricie API always. We use a static IP address for the server, so we need not have to worry about the IP address change.

Can you please work with Tourisme Mauricie to whitelist the IP address: **3.97.145.197**. Please let us know once done.

**Comment by tammy-culture** [comment]
@sahalali The IP address is whitelisted, done.

**Comment by tammy-culture** [comment]
Hi @sahalali,

Caligram does not have the ability to provide a CSV file for Culture Mauricie, but they do have 2 APIs (which I never thought to ask for).

Here are the two API access points they provided:

(1) Get a list of all upcoming events: https://culturemauricie.caligram.com/api/events

(2) Obtain detailed information about an event (necessary to obtain all the dates of an event): https://culturemauricie.caligram.com/api/events/[id]

For more information, here's the API documentation: http://api.caligram.com

**Can you use the above APIs?**  Or do we scrape/crawl the site?  

Please let me know when you can.

Thanks.

**Comment by sahalali** [comment]
@tammy-culture We can use the above APIs. 
We will be able to upload the data using the footlight aggregator with a new API with minimum development effort.

**Comment by sahalali** [comment]
@tammy-culture is Caligram API the 4th source for the Culture Mauricie calendar?

**Comment by tammy-culture** [comment]
@sahalali The Caligram API is for the current Culture Mauricie cultural calendar called (D'ici.ca).  When we decide to officially do a LAST transfer of data from Caligram API to the Culture Mauricie Calendar, this API will no longer be needed as a source.  It is being used only to transfer events from the current calendar to Footlight CMS.  

Does this make sense?

**Comment by sahalali** [comment]
Yes.

**Comment by saumier** [comment]
@sahalali For the video URL you can use: 
```
"http://schema.org/recordedIn":  "https://www.youtube.com/embed/-LtoFSrT3Bk"
```

And for the contact point you can use:
```
"http://schema.org/contactPoint" : 
 {
    "@type": "http://schema.org/ContactPoint",
    "http://schema.org/email": "infoloisirsbma@gatineau.ca",
    "http://schema.org/telephone": "8199312902",
    "http://schema.org/url": "http://thewebsite.com",
    "http://schema.org/name": [
      {
        "@language": "fr",
        "@value": "Soutien et relations avec les communautés"
      }
    ]
 }

```

**Comment by tammy-culture** [comment]
Hi @sahalali, I noticed for single date occurrences in acaligram, the dates appear as a date range rather than a single date.  Is there a way to fix this?

<img width="834" alt="Screenshot 2024-02-02 at 09 21 22" src="https://github.com/culturecreates/footlight-aggregator/assets/45608438/0c643929-4b37-4211-88c6-fa497a846a0f">

**Comment by sahalali** [comment]
I will look into this @tammy-culture

**Comment by tammy-culture** [comment]
@sahalali When I added the Taxonomy for event types in production, I took the time to put the event types in alphabetical order.  I see now that it is no longer the case in both production and staging.  Is there a way of making sure the order is respected? Thanks.

![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/f223d772-213e-4b45-bf7d-acbdfd1402d4)

**Comment by sahalali** [comment]
I cleaned up taxonomy last day and removed a few concepts that I added and no longer required. I think the reordering might have happened then.

The order should persist always until the user makes any change.

**Comment by sahalali** [comment]
As per the discussion during today's standup
1. Import events to the Culture Mauricie Calendar in the Production.
2. The unpublished events from Caligram should not be imported to CMS.

**Comment by tammy-culture** [comment]
@sahalali I noticed that the CMS production is missing quite a few Event Types from Caligram,, is this normal.  Thanks.

**Comment by sahalali** [comment]
@tammy-culture  I will check it.

**Comment by sahalali** [comment]
@tammy-culture The issue was related to a mapping file we use to map the event type from the source to CMS. The issue is now fixed.
Assigning this issue to you @tammy-culture for review. If you see any issues, please assign this issue back to me.

**Comment by tammy-culture** [comment]
Hi @sahalali I still notice a problem with missing event types.

Here is an event in Footlight production with a missing Event Type:



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/1ca1dd37-7970-4f5f-837c-c0f208c6db6d)


Here is how this same event appears on the current Culture Mauricie event listing website called D'ici.ca.  Notice on the top left had corner MUSIQUE which indicated the event type.  I am assuming that event types are availabe in the acaligram API.  Is that right?



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/c29a478c-2fb5-4d80-a11c-c4f6949b8e35)


Can we fix this?

Thanks.

**Comment by tammy-culture** [comment]
Here is another example.

What we have for an event in Production CMS - the event type is missing.


![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/2ca744af-e126-4e97-b6a3-218e3615ced2)

Versus the event type indicated on the webpage - THÉÂTRE - in the top left hand corner.



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/dfe1d218-307c-4447-9558-e097ca0cb615)

Here is a link to the actual webpage: https://dici.ca/evenements/theatre-des-gens-de-la-place-les-botuliques

Thanks.

**Comment by tammy-culture** [comment]
@sahalali In the acaligram user the Event URLs are not correct.  Here is an example:
<img width="493" alt="Screenshot 2024-02-14 at 09 34 18" src="https://github.com/culturecreates/footlight-aggregator/assets/45608438/8f27cea0-8b88-4346-a09d-c26b6b0c27af">

This link (http://culturemauricie.com/evenements/peaux-d-ames/25379) is broken and goes no where.

Here is a link to the current event page : https://dici.ca/evenements/peaux-d-ames

I think I need clarification on what URL is needed in this field.

Thanks.

**Comment by tammy-culture** [comment]
@sahalali 
The additional event types are looking good!

**Comment by tammy-culture** [comment]
@sahalali 
I just spoke with the client and I have the following question:

It looks like Place addresses from the acaligram user are not appearing in the production CMS  - even though addresses are available in acaligram (I confirmed with the client).

Is there a way to fix this ? Does this have anything to do with issue #971 ?

Many thanks,
Tammy

**Comment by sahalali** [comment]
Event URL:
The eventURL in the Caligram API responses for both event listing and event details are broken URLs.

I could not find a way to create non-breaking URLs from the API responses.

I think we should remove these eventURLs from the CMS unless we find the correct URLs. What do you think @tammy-culture?

I've added the API responses below for reference. 

Here is the resposne from event listing:
 `{
      "id": 25379,
      "title": "Peaux d'âmes",
      "slug": "peaux-d-ames",
      "description": "<p>François Bertrand, sculpteur textile <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=21bf5da879&amp;e=ceedd7cf80\">François Bertrand</a> est né à Montréal en 1961 et vit à Québec depuis 1981. Il a travaillé comme expert-conseil en psychiatrie pendant plus de 30 ans et comme psychologue en pratique privée pendant une dizaine d’années. En 2001, il fonde le <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=c2446d6110&amp;e=ceedd7cf80\">Programme Vincent et moi</a> à l’Institut universitaire en santé mentale de Québec, aujourd’hui CIUSSS de la Capitale-Nationale. Par le biais de ce programme dédié aux artistes en arts visuels vivant avec la maladie mentale, il lutte pour faire connaître et reconnaître leur contribution artistique et culturelle. À cette fin, il ouvre entre autres, la <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=6786a186e8&amp;e=ceedd7cf80\">Galerie Vincent et moi </a>en 2013. </p>",
      "start_date": "2023-05-01T10:00:00.000000Z",
      "end_date": "2024-03-31T17:00:00.000000Z",
      "next_date": "2024-02-15 10:00:00",
      "event_dates_count": 46,
      "venues_count": 1,
      "display_image_url": ["https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg"](https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg),
      "photo_url": ["https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg"](https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg),
      "public": true,
      "extra_large_photo_url": ["https://cdn.caligram.com/uploads/event/wOX/xlarge/644fc6ddc7663.jpg"](https://cdn.caligram.com/uploads/event/wOX/xlarge/644fc6ddc7663.jpg),
      "thumbnail_url": ["https://cdn.caligram.com/uploads/event/wOX/thumbnail/644fc6ddc7663.jpg"](https://cdn.caligram.com/uploads/event/wOX/thumbnail/644fc6ddc7663.jpg),
      "website_url": null,
      "lang": "fr",
      "created_at": "2023-05-01T14:04:31+00:00",
      "updated_at": "2023-05-01T17:31:28+00:00",
      "featured": false,
      "url": ["http://culturemauricie.com/evenements/peaux-d-ames/25379"](http://culturemauricie.com/evenements/peaux-d-ames/25379),
      "calendar_id": 38,
      "status": "published",
      "translations": [
        {
          "locale": "fr",
          "path": ["http://culturemauricie.com/evenements/peaux-d-ames/25379"](http://culturemauricie.com/evenements/peaux-d-ames/25379)
        }
      ],
      "author": {
        "user_id": 1799,
        "name": "Alexis Vaillant-Gamache"
      },
      "tags": [ ],
      "venue": {
        "id": 8165,
        "cc_id": null,
        "eb_id": null,
        "name": "Musée POP",
        "slug": "musee-pop",
        "description": null,
        "other_names": "",
        "address": "200 Rue Laviolette Suite 1",
        "address2": null,
        "city": "Trois-Rivières",
        "state": null,
        "country": null,
        "zip": "G9A 6L5",
        "region_id": 506,
        "latitude": 46.3447446,
        "longitude": -72.5401555,
        "phone": "819-372-0406",
        "telephone": "819-372-0406",
        "website_url": ["https://museepop.ca/"](https://museepop.ca/),
        "link": ["https://museepop.ca/"](https://museepop.ca/),
        "business_hours": null,
        "created_at": "2021-10-05T18:05:28+00:00",
        "updated_at": "2021-10-05T18:05:28+00:00"
      },
      "types": [
        {
          "id": 31,
          "parent_id": 22,
          "name": "Exposition",
          "slug": "exposition-ou-vernissage"
        }
      ]
    }`

Here is the event details API response:
`{
  "id": 25379,
  "contact_email": "",
  "contact_name": "",
  "contact_phone": "",
  "contact_url": "",
  "date_notes": null,
  "description": "<p>François Bertrand, sculpteur textile <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=21bf5da879&amp;e=ceedd7cf80\">François Bertrand</a> est né à Montréal en 1961 et vit à Québec depuis 1981. Il a travaillé comme expert-conseil en psychiatrie pendant plus de 30 ans et comme psychologue en pratique privée pendant une dizaine d’années. En 2001, il fonde le <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=c2446d6110&amp;e=ceedd7cf80\">Programme Vincent et moi</a> à l’Institut universitaire en santé mentale de Québec, aujourd’hui CIUSSS de la Capitale-Nationale. Par le biais de ce programme dédié aux artistes en arts visuels vivant avec la maladie mentale, il lutte pour faire connaître et reconnaître leur contribution artistique et culturelle. À cette fin, il ouvre entre autres, la <a href=\"https://museepop.us5.list-manage.com/track/click?u=3477a542e061fe9951fb61499&amp;id=6786a186e8&amp;e=ceedd7cf80\">Galerie Vincent et moi </a>en 2013. </p>",
  "end_date": "2024-03-31 17:00:00",
  "event_dates_count": 336,
  "facebook_url": "",
  "display_image_url": "https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg",
  "photo_url": "https://cdn.caligram.com/uploads/event/wOX/medium/644fc6ddc7663.jpg",
  "price_currency": "CAD",
  "price_notes": null,
  "price_type": "FIXED",
  "public": true,
  "recurring": false,
  "short_description": null,
  "show_counter": null,
  "slug": "peaux-d-ames",
  "start_date": "2023-05-01 10:00:00",
  "subscription": {
    "type": null,
    "email": "",
    "phone": "",
    "url": ""
  },
  "thumbnail_url": "https://cdn.caligram.com/uploads/event/wOX/thumbnail/644fc6ddc7663.jpg",
  "ticket_url": "https://museepop.ca/planifiez-votre-visite/horaire-et-tarifs",
  "title": "Peaux d'âmes",
  "video": null,
  "video_url": "",
  "lang": "fr",
  "created_at": "2023-05-01T14:04:31+00:00",
  "updated_at": "2023-05-01T17:31:28+00:00",
  "featured": false,
  "url": "http://culturemauricie.com/evenements/peaux-d-ames/25379",
  "calendar_id": 38,
  "status": "published",
  "translations": [
    {
      "locale": "fr",
      "path": "http://culturemauricie.com/evenements/peaux-d-ames/25379"
    }
  ],
  "audiences": [ ],
  "author": {
    "user_id": 1799,
    "name": "Alexis Vaillant-Gamache"
  },
  
  "venue": {
    "id": 8165,
    "cc_id": null,
    "eb_id": null,
    "name": "Musée POP",
    "slug": "musee-pop",
    "description": null,
    "other_names": "",
    "address": "200 Rue Laviolette Suite 1",
    "address2": null,
    "city": "Trois-Rivières",
    "state": null,
    "country": null,
    "zip": "G9A 6L5",
    "region_id": 506,
    "latitude": 46.3447446,
    "longitude": -72.5401555,
    "phone": "819-372-0406",
    "telephone": "819-372-0406",
    "website_url": "https://museepop.ca/",
    "link": "https://museepop.ca/",
    "business_hours": null,
    "created_at": "2021-10-05T18:05:28+00:00",
    "updated_at": "2021-10-05T18:05:28+00:00"
  }
}`

**Comment by sahalali** [comment]
As per today's standup discussion,
We will remove the broken eventUrls from the caligram.

**Comment by sahalali** [comment]
Removed event-url from while importing to CMS. Re-imported events to CMS.

For those events that are updated by other users, the event URL (breaking URLs) will not removed, as those events cannot be updated by the calligram user anymore.

**Comment by tammy-culture** [comment]
@sahalali Here is another example of the wrong event type.



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/10af8f2c-a473-40b7-bc3c-3ca7430fee2c)

https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c7237f90c70063661682

It should be CHANSON



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/91450454-c28a-4d1e-b45e-b590751e73fe)

https://dici.ca/evenements/elisapie-inuktitut

**Comment by tammy-culture** [comment]
@sahalali The Event urls are still appearing everywhere.



![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/da548f60-0081-4fea-ac45-37740f95d83a)

**Comment by sahalali** [comment]
@tammy-culture 
We had an issue with the Caligram import which caused the event tags to be not imported. It is fixed now but I have a question.
https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c7237f90c70063661682 this event has an event tag(Chanson) as well as an event type(Spectacle). But on the client's website, we only see the tag. So should we consider saving event types moving forward?

**Comment by sahalali** [comment]
The issue with importing tags is fixed. Also removed breaking event URLs manually running a script.

**Comment by tammy-culture** [comment]
@sahalali RE: The event tag and event types.  I will ask the client and get back to you.

**Comment by sahalali** [comment]
Now, we are importing both event types and tags.

**Comment by tammy-culture** [comment]
Hi @sahalali , I noticed that the field "Buy Tickets Link" is not be uploaded from the acaligram user.  

Here is an example in the Production CMS
<img width="740" alt="Screenshot 2024-02-19 at 08 48 09" src="https://github.com/culturecreates/footlight-aggregator/assets/45608438/2200b457-5cfd-40d1-b19d-12a1215e4dd5">

https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c90f7f90c70063664610

And the event webpage the Buy tickets Link appears as ACHAT.
<img width="1641" alt="Screenshot 2024-02-19 at 08 53 08" src="https://github.com/culturecreates/footlight-aggregator/assets/45608438/b84933b0-34c3-4a3f-9356-ff4c09e1bc5d">

ANd when you click on [ACHAT]  it brings you to a purchase page: https://shawinigan.ticketacces.net/fr/organisation/representations/index.cfm?EvenementID=10836&Date=&refresh=1

Can we fix this?

Many many thanks.

**Comment by tammy-culture** [comment]
Hi @sahalali,

Here is what I have found in my review of the acaligram user in regards to events that are missing a Buy Url Ticket Link:

(1) In Production CMS: [DRAG](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c9167f90c700636646ac).  Here is the actual [webpage link](https://dici.ca/evenements/drag-2) and [ticket link](https://billets.amphitheatrecogeco.com/atr/?locale=fr-CA&skin=ampcogeco&fac=ATR#/71530d2e-ee90-4436-a3aa-be5920a5ea50/shop/search?fac=ATR&locale=fr-CA&skin=ampcogeco).

(2) In Production CMS: [Pierre Lapointe : Chansons hivernales](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c8fd7f90c70063664453). Here is the actual [Webpage Link ](https://dici.ca/evenements/pierre-lapointe-chansons-hivernales-1)and [Ticket Link](https://shawinigan.ticketacces.net/fr/organisation/representations/index.cfm?EvenementID=10844)

(3) In Production CMS: [Sara Dufour](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c7da7f90c7006366282b). I cannot find the Webpage Link on the D'ici.ca calendar. I did find the actual event on the Amphitheatre Cogeco [website](https://www.amphitheatrecogeco.com/spectacles/sara-dufour).  There are other things going wrong with this event as well. The time is not correct - it is not aligned with what is on the event webpage. Perhaps this is a bad entry in Caligram?

(4) In Production CMS: [Francis Degrandpré](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c79d7f90c70063662225). _A-ha_, the Buy Url Ticket Link does not appear on the actual [calendar webpage](https://dici.ca/evenements/francis-degrandpre).  Instructions to purchase tickets are written in the description, so there is no error here, just a weird entry into Caligram.

(5) In Production CMS: [Souldia](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c77b7f90c70063661eec). Another case of the Buy Url Ticket Link not appearing on the actual [webpage](https://dici.ca/evenements/souldia-5).


I think these are edge cases and everything else looks really good.

Thank you.

**Comment by sahalali** [comment]
1. The issue with DRAG is now fixed with reimporting.
2. [Pierre Lapointe : Chansons hivernales](https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65c9c8fd7f90c70063664453) is getting updated as its modified by other user.
3. The issue with the time was due to a glitch in the import script. Its now fixed and reuploaded.

**Comment by tammy-culture** [comment]
@sahalali  RE: The event tag and event types. I confirmed with the client and all they want are the event tags to appear in the Production CMS Event Type. field.

Example: For Elisapie : Inuktitut, all they want is CHANSON to appear and not Improvisation. They just want one to appear.


![Image](https://github.com/culturecreates/footlight-aggregator/assets/45608438/fee9de7c-0050-47c3-9c1f-55dd26303bee)

Let me know if you need more examples and many many thanks.

Tammy

**Comment by sahalali** [comment]
@tammy-culture 
I see a case where an event does not have a tag but a eventType. In that eventType is used to display the label in the wensite.

API response: https://culturemauricie.caligram.com/api/events/27779
Webpage for this event: https://dici.ca/evenements/ariane-cardinal-developpement-de-la-sphere-educative-dans-les-lieux-de-diffusion-en-art-visuel
Event in CMS https://cms.footlight.io/dashboard/657199fea5ac3d006314ea92/events/add-event/65d58d0a79151d0064f30263


For this event the API response only had event_type (conference), no event tags. So there is no type for it in CMS. But when I checked their webpage, the event has a type called 'conference'.  If we are considering only keeping the event_tag in the CMS, we might lose some event types.
